<a href="https://colab.research.google.com/github/chonzadaniel/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00_PyTorch Fundamentals



In [ ]:
print("Hello, I'm excited to learn PyTorch")

Hello, I'm excited to learn PyTorch


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


# Introduction to Tensors

# Creating Tensors

# Scalar

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.shape

torch.Size([])

# Get Tensor Back as Python Int

In [ ]:
scalar.item()

7

# Vector

In [ ]:
## Creating a Vector:

vector = torch.tensor(
    [7, 7]
)

vector

tensor([7, 7])

In [ ]:
# Checking for vector dimension
vector.ndim

1

In [ ]:
# Checking for Vector shape

vector.shape

torch.Size([2])

# Creating MATRIX in Using Torch through the Tensor method

In [ ]:
MATRIX = torch.tensor(
    [[7, 8],
     [9, 10]]
)

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

# Checking for MATRIX dimension


In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

# CREATING TENSORS

In [ ]:
TENSOR = torch.tensor(
    [[[1, 2, 3],
      [3, 6, 9],
      [2, 4, 5]]]
)

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Creating Random Tensors

## Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

Start with randam numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# Creating random tensors

random_tensor = torch.rand(3, 4)

In [ ]:
 # Visualising the tensor

 random_tensor

tensor([[0.8659, 0.7448, 0.7857, 0.1338],
        [0.0392, 0.9851, 0.0186, 0.5340],
        [0.4072, 0.4336, 0.1671, 0.3775]])

In [ ]:

random_tensor1 = torch.rand(5, 10, 10)
random_tensor1

tensor([[[0.3429, 0.8423, 0.0227, 0.1739, 0.4202, 0.2260, 0.2901, 0.3523,
          0.5056, 0.6911],
         [0.7894, 0.9201, 0.9236, 0.0713, 0.0299, 0.7487, 0.2063, 0.0041,
          0.5386, 0.1253],
         [0.7180, 0.7363, 0.4132, 0.8077, 0.0294, 0.5687, 0.7777, 0.0105,
          0.6889, 0.1463],
         [0.4364, 0.6577, 0.4015, 0.5916, 0.0340, 0.0485, 0.2991, 0.6696,
          0.3423, 0.3056],
         [0.7399, 0.7948, 0.5873, 0.8981, 0.1839, 0.9525, 0.7079, 0.5011,
          0.1213, 0.5535],
         [0.0398, 0.8814, 0.9341, 0.9840, 0.2267, 0.8671, 0.4333, 0.1878,
          0.5862, 0.6145],
         [0.7642, 0.5085, 0.6788, 0.0928, 0.6671, 0.6151, 0.6743, 0.3326,
          0.8657, 0.7429],
         [0.5359, 0.1215, 0.1725, 0.6630, 0.3649, 0.5363, 0.4383, 0.5281,
          0.3366, 0.7424],
         [0.7189, 0.0939, 0.3089, 0.4975, 0.1049, 0.8952, 0.7949, 0.9185,
          0.0893, 0.8957],
         [0.1980, 0.4850, 0.7679, 0.0059, 0.1078, 0.1605, 0.2281, 0.6902,
          0.5394,

# Creating the Random Image Size Tensors

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width (R, G, B)


In [ ]:
# Visualizing the Tensor Shape and Dimension
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

* The shape and dimension above could be visualized separately as indicated below:

In [ ]:
# Visualizing the Tensor Shape
random_image_size_tensor.shape


torch.Size([3, 224, 224])

In [ ]:
# Visualizing the Tensor Dimension
random_image_size_tensor.ndim


3

# Ones and Zeros

In [ ]:
# Zeros Tensor

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Ones Tensor

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## The default data type of tensors is float

# Creating a Range of Tensors and Tensors-like

In [ ]:
zero_to_ten_tensor = torch.arange(0, 11)
zero_to_ten_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten_tensor_range = torch.arange(1, 11)
one_to_ten_tensor_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten_tensor = torch.arange(start=1, end=11, step=1)
one_to_ten_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
step_tensor_range = torch.arange(start=1, end=500, step=67)
step_tensor_range

tensor([  1,  68, 135, 202, 269, 336, 403, 470])

# Creating Tensors Like

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatype

**Note**: Tensor datatype is oneof the 3 error you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

# Precision in Computing:-> https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tenso (e.g. float32 or float16)
                               device=None, # What device is your tensor on.
                               requires_grad=False, # Whether or not to track gradients with this tensors operation.
                              )

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Converting the default tensor float32 datatype to tensor float16 datatype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

**Note**: One may also use 'torch.half' to change the tensor float32 to tensor float16 datatype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors


1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device


# Create a tensor

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6464, 0.6677, 0.5853, 0.8910],
        [0.3410, 0.6359, 0.4802, 0.5727],
        [0.3949, 0.9072, 0.4159, 0.5210]])

In [ ]:
# Finding out details about some tensor
print("The tensor created is:\n")
print(some_tensor)
print()
print(f"Datatype of tensor: {some_tensor.dtype}\n")
print(f"Shape of tensor: {some_tensor.shape}\n")
print(f"Device tensor is on: {some_tensor.device}")


The tensor created is:

tensor([[0.6464, 0.6677, 0.5853, 0.8910],
        [0.3410, 0.6359, 0.4802, 0.5727],
        [0.3949, 0.9072, 0.4159, 0.5210]])

Datatype of tensor: torch.float32

Shape of tensor: torch.Size([3, 4])

Device tensor is on: cpu


# Manipulating Tensors (tensor operations)

Tensor operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add numbers on it

tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
# Adding up a number on a tensor
tensor + 10


tensor([11, 12, 13])

In [ ]:
tensor + 100

tensor([101, 102, 103])

In [ ]:
# Multiplication of tensor by a number

tensor * 20

tensor([20, 40, 60])

In [ ]:
# Subtracting a number from a tensor

tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Using in-built fucntions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 15)

tensor([16, 17, 18])

# Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplicaiton
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

# There are two mail rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:

* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2)` -> `(2, 3)`
* `(3, 2) @ (2, 3)` - > `(3, 3)`

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.7199, 0.5814, 0.5064],
        [1.0217, 0.6635, 0.8942],
        [0.2886, 0.2725, 0.1602]])

In [ ]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Throwing an Error:

# torch.matmul(torch.rand(10, 10), torch.rand(7, 10)).shape

### This is because of in the inner dimensions mismatch.

In [ ]:
torch.matmul(torch.rand(10, 7), torch.rand(7, 10)).shape

torch.Size([10, 10])

# Fiding the min, max, mean, sum, etc. (tensor aggregation)

In [ ]:
# Creating a tensor

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Finding the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

# Finding the position min and max

In [ ]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() and -> return index position of target tensor where the minimum value with argmin()

x.argmin()

tensor(0)

In [ ]:
# Find the postion in tensor that has the maximum value with argmax()

x.argmax()

tensor(9)

In [ ]:
# Finding the value at a certain position number in a tensor

x[9]

tensor(91)

In [ ]:
x[4]

tensor(41)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape.
* view - Returns a view of an input tensor of certain shape but keep the same memory as the original tensor.
*  Stacking - Combines multiple tensors on top of each other (torch.vstack) or side by side (torch.hstack).
* Squeeze - Removes all `1` dimension to a target tensor.
* Permute - Returns a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
# First creating a tensor
import torch
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
x_reshaped1 = x.reshape(5, 2)
x_reshaped1, x_reshaped1.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
x_reshaped2 = x.reshape(2, 5)
x_reshaped2, x_reshaped2.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# First creating a tensor

import torch
x = torch.arange(1., 13.)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
# Add an extra dimension

x_reshaped = x.reshape(2, 6)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

In [ ]:
x_reshaped1 = x.reshape(6, 2)
x_reshaped1, x_reshaped1.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [ ]:
# Change the view
z = x.view(1, 12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)

z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [ ]:
z[:,5] = 10
z, z.shape, x, x.shape

(tensor([[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]),
 tensor([ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
torch.stack([z, z, z, z, z, z, z])

tensor([[[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.]]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor

# Creating a tensor
import torch
x = torch.arange(1., 13.)

x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
torch.squeeze(x)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
z = x.reshape(2, 6)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

In [ ]:
x = torch.zeros(2, 12)
x

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y.shape

torch.Size([2, 2, 2])

#### shape and size() method work in a similar fation displaying the dimension size of a tensor

# Returning a tensor to original dimensions

In [ ]:
y = torch.squeeze(x, 0)
print(f"Printing squeezed tensor using size() method: {y.size()}\n")
print(f"Printing the squeezed tensor dimension using shape approach: {y.shape}")

Printing squeezed tensor using size() method: torch.Size([2, 1, 2, 1, 2])

Printing the squeezed tensor dimension using shape approach: torch.Size([2, 1, 2, 1, 2])


In [ ]:
x


tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [ ]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor.

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")


# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


## torch.permute - rearranges the dimensions of a target tensor in a specified order

In [ ]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
print(x_original)

tensor([[[7.9637e-01, 7.6920e-01, 5.6365e-01],
         [1.1120e-01, 2.3287e-01, 6.0405e-01],
         [7.0256e-01, 8.7264e-01, 4.0925e-01],
         ...,
         [8.2857e-01, 8.4893e-01, 1.9614e-01],
         [9.6073e-01, 8.9982e-01, 9.7591e-01],
         [8.1705e-01, 8.8987e-01, 7.3322e-01]],

        [[6.6972e-01, 1.5532e-01, 4.0700e-01],
         [1.0366e-01, 1.1499e-01, 3.4785e-01],
         [3.4701e-01, 8.0699e-01, 4.4370e-01],
         ...,
         [4.7263e-01, 9.2271e-02, 4.3040e-01],
         [8.9201e-02, 5.1670e-01, 7.2923e-01],
         [8.5886e-01, 6.6796e-01, 2.3455e-01]],

        [[1.4822e-01, 4.5447e-01, 6.6416e-01],
         [1.9792e-01, 5.8292e-01, 3.6714e-02],
         [4.5300e-01, 9.5694e-01, 5.2037e-01],
         ...,
         [1.4987e-01, 4.4645e-01, 2.0837e-02],
         [8.7017e-01, 4.4500e-01, 9.0045e-01],
         [3.7596e-01, 8.8139e-01, 1.1333e-01]],

        ...,

        [[7.8028e-01, 1.7294e-01, 6.5029e-04],
         [8.3568e-01, 2.5305e-01, 6.7959e-02]

# Permute the original tensor to rearrange the axis (or dim) order.

In [ ]:
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 ->0
print(x_permuted)
x_permuted.shape

tensor([[[7.9637e-01, 1.1120e-01, 7.0256e-01,  ..., 8.2857e-01,
          9.6073e-01, 8.1705e-01],
         [6.6972e-01, 1.0366e-01, 3.4701e-01,  ..., 4.7263e-01,
          8.9201e-02, 8.5886e-01],
         [1.4822e-01, 1.9792e-01, 4.5300e-01,  ..., 1.4987e-01,
          8.7017e-01, 3.7596e-01],
         ...,
         [7.8028e-01, 8.3568e-01, 7.5254e-01,  ..., 6.1760e-01,
          2.2049e-01, 5.0641e-01],
         [7.6081e-01, 3.7834e-01, 1.3160e-01,  ..., 9.0941e-01,
          1.5100e-01, 3.6164e-01],
         [6.6028e-03, 9.2525e-01, 3.6618e-01,  ..., 2.3751e-01,
          9.2867e-01, 7.4050e-01]],

        [[7.6920e-01, 2.3287e-01, 8.7264e-01,  ..., 8.4893e-01,
          8.9982e-01, 8.8987e-01],
         [1.5532e-01, 1.1499e-01, 8.0699e-01,  ..., 9.2271e-02,
          5.1670e-01, 6.6796e-01],
         [4.5447e-01, 5.8292e-01, 9.5694e-01,  ..., 4.4645e-01,
          4.4500e-01, 8.8139e-01],
         ...,
         [1.7294e-01, 2.5305e-01, 9.2995e-01,  ..., 3.8245e-01,
          9.715

torch.Size([3, 224, 224])

In [ ]:
y_original = torch.rand(size=(52, 52, 3))
print(y_original)
print(y_original.shape)

tensor([[[1.3439e-01, 6.5457e-01, 4.2285e-03],
         [6.9216e-01, 1.3614e-01, 4.0542e-01],
         [4.5684e-01, 5.8821e-02, 6.2725e-01],
         ...,
         [3.9072e-01, 1.2030e-01, 9.7182e-01],
         [2.0480e-01, 1.5979e-01, 9.3318e-01],
         [1.1993e-01, 4.9866e-01, 6.2599e-01]],

        [[8.8100e-02, 8.0188e-02, 3.1293e-01],
         [4.9567e-01, 4.0629e-01, 6.7190e-01],
         [2.4037e-02, 8.4920e-01, 6.6019e-01],
         ...,
         [2.2176e-01, 7.8265e-01, 7.0461e-01],
         [7.3520e-01, 9.5962e-02, 5.2262e-01],
         [5.9840e-01, 3.5172e-02, 5.3889e-01]],

        [[1.3789e-01, 1.5508e-01, 1.6103e-01],
         [8.1785e-01, 2.4592e-01, 3.3083e-01],
         [8.4809e-01, 1.9988e-01, 1.6837e-02],
         ...,
         [7.0846e-01, 1.3861e-01, 4.3652e-01],
         [1.6200e-01, 5.7746e-01, 6.5318e-01],
         [4.4282e-01, 1.8886e-02, 1.4177e-01]],

        ...,

        [[9.7068e-01, 9.8565e-01, 1.2726e-04],
         [4.0504e-01, 4.5180e-01, 9.3861e-01]

In [ ]:
y_permuted = y_original.permute(2, 1, 0)
print(y_permuted)
print(y_permuted.shape)

tensor([[[1.3439e-01, 8.8100e-02, 1.3789e-01,  ..., 9.7068e-01,
          5.4939e-01, 9.9898e-01],
         [6.9216e-01, 4.9567e-01, 8.1785e-01,  ..., 4.0504e-01,
          2.4463e-01, 6.7657e-01],
         [4.5684e-01, 2.4037e-02, 8.4809e-01,  ..., 2.3754e-01,
          1.9343e-01, 1.0162e-01],
         ...,
         [3.9072e-01, 2.2176e-01, 7.0846e-01,  ..., 1.8941e-01,
          8.9657e-01, 7.3010e-01],
         [2.0480e-01, 7.3520e-01, 1.6200e-01,  ..., 3.9845e-01,
          2.4349e-01, 7.6075e-01],
         [1.1993e-01, 5.9840e-01, 4.4282e-01,  ..., 9.4334e-01,
          7.2196e-01, 3.8200e-01]],

        [[6.5457e-01, 8.0188e-02, 1.5508e-01,  ..., 9.8565e-01,
          7.2917e-01, 6.7963e-02],
         [1.3614e-01, 4.0629e-01, 2.4592e-01,  ..., 4.5180e-01,
          4.1000e-01, 3.1328e-01],
         [5.8821e-02, 8.4920e-01, 1.9988e-01,  ..., 6.2106e-01,
          5.0005e-01, 6.4798e-01],
         ...,
         [1.2030e-01, 7.8265e-01, 1.3861e-01,  ..., 3.0771e-01,
          1.885

In [ ]:
x_permuted.size()

torch.Size([3, 224, 224])

In [ ]:
y_permuted.size()

torch.Size([3, 52, 52])

In [ ]:
# summary
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}\n") # [color_channels, height, width]

# summary
print(f"Previous shape: {y_original.shape}")
print(f"New shape: {y_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])

Previous shape: torch.Size([52, 52, 3])
New shape: torch.Size([3, 52, 52])


# Indexing (selecting data from tensors)

* Indexing with PyTorch is a similar to indexing with NumPy

In [ ]:
# Creating a tensor
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Creating a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Selecting 5 from Tensor 'x'
x[0, 1, 1]

tensor(5)

In [ ]:
# Selecting 9

x[0, 2, 2]

tensor(9)

In [ ]:
# Selecting 6

x[0, 1, 2]

tensor(6)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:1,0]

tensor([[1, 2, 3]])

In [ ]:
x[:2, 1]

tensor([[4, 5, 6]])

In [ ]:
x[:3, 2]

tensor([[7, 8, 9]])

In [ ]:
x[:,2]

tensor([[7, 8, 9]])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

# Summary

In [ ]:
# Print tensor and its shape
print("Tensor x:\n", x)
print("Shape of tensor x:", x.shape)

# Iterate over each element in the tensor
# Since it's a 3-dimensional tensor but only one in the first dimension, iterate over the second and third dimensions
for i in range(x.shape[1]):  # x.shape[1] is the size of the second dimension (rows)
    for j in range(x.shape[2]):  # x.shape[2] is the size of the third dimension (columns)
        # Print the index (i, j) and the element at that index
        print(f'Element at index [{0}, {i}, {j}] = {x[0, i, j]}')

Tensor x:
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape of tensor x: torch.Size([1, 3, 3])
Element at index [0, 0, 0] = 1
Element at index [0, 0, 1] = 2
Element at index [0, 0, 2] = 3
Element at index [0, 1, 0] = 4
Element at index [0, 1, 1] = 5
Element at index [0, 1, 2] = 6
Element at index [0, 2, 0] = 7
Element at index [0, 2, 1] = 8
Element at index [0, 2, 2] = 9


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless spefied otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

#### As one may notice, the default datatype for NumPy array is `float64`, which is a long datatype for tensor, making it incompatible to the default `float32` tensor datatype

In [ ]:
array.dtype


dtype('float64')

In [ ]:
# Compare to a tensor
torch.arange(1., 8.).dtype

torch.float32

In [ ]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

Already discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.6051, 0.9051, 0.7420, 0.8004],
        [0.0850, 0.4911, 0.0383, 0.2841],
        [0.1551, 0.2428, 0.3200, 0.8501]])

Tensor B:
tensor([[0.3406, 0.3775, 0.3798, 0.4443],
        [0.7622, 0.5748, 0.0833, 0.8258],
        [0.5987, 0.8232, 0.0741, 0.1314]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

# Is true that the two Tensors A & B change everytime the cell is run.

# Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

# So you can perform repeatable experiments.

** For example, you create an algorithm capable of achieving X performance.

** And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

* That's where reproducibility comes in.

** In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

** Let's see a brief example of reproducibility in PyTorch.

** Start by creating two random tensors, since they're random, you'd expect them to be different right?

In [ ]:
# Making some random but reproducible tensors

import torch

# Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)


print(f"Random Tensor C:\n {random_tensor_C}\n")
print(f"Random Tensor D: \n {random_tensor_D}\n")
print(f"Two Tensors Comparison: \n {random_tensor_C == random_tensor_D}")

Random Tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Random Tensor D: 
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

Two Tensors Comparison: 
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# Solution to the changing `randomness` behaviour above

In [ ]:
# Making some random but reproducible tensors

import torch

# Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)


print(f"Random Tensor C:\n {random_tensor_C}\n")
print(f"Random Tensor D: \n {random_tensor_D}\n")
print(f"Two Tensors Comparison: \n {random_tensor_C == random_tensor_D}")

Random Tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Random Tensor D: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Two Tensors Comparison: 
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Extra Resources for reproducibility:

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

# Running tensors on GPUs (and making faster computations)

## Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

**Note**: When I reference "GPU" throughout this course, I'm referencing a Nvidia GPU with CUDA enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.

## Checking for GPU access with PyTorch

In [ ]:
# Checking or GPU access with PyTorch

import torch

torch.cuda.is_available()

False

In [ ]:
# Setting up device agnostic code:

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Counting number of devices

torch.cuda.device_count()

0

* Due to the structure of PyTorch, there is need to explicitly write decive-agnostic (CPU or GPU) code.

* A common pattern is to use Python's argparse module to read in user agruments, and have a flag that can be used to disable CUDA, in combination with `is_available()`.

* In the following, `args.device` results in a `torch.device` object that can be used to move tensors to CPU or CUDA.

In [ ]:
# import argparse
# import torch

# parser = argparse.ArgumentParser(description='PyTorch Exmaple')
# parser.add_argument('--disable-cuda', action='store_true',
#                     help='Disable CUDA')
# args = parser.parse_args()
# args.device = None
# if not args.disable_cuda and torch.cuda.is_available():
#     args.device = torch.device('cuda')
# else:
#     args.device = torch.device('cpu')

In [ ]:
# import argparse
# import torch

# # Set up argument parser
# parser = argparse.ArgumentParser(description='PyTorch Example')
# parser.add_argument('--disable-cuda', action='store_true',
#                     help='Disable CUDA to force using CPU even if CUDA is available')

# # Parse arguments
# args = parser.parse_args()

# # Determine the device based on the availability of CUDA and user input
# if not args.disable_cuda and torch.cuda.is_available():
#     args.device = torch.device('cuda')
# else:
#     args.device = torch.device('cpu')

# # Optionally, print out the device that will be used
# print(f"Using device: {args.device}")
